using System.Net;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

public class AdminSupportTests:IDisposable {
    readonly TestDatabase database=new();
    readonly WebApplicationFactory<Program> factory;
    public AdminSupportTests(){factory=new WebApplicationFactory<Program>().WithWebHostBuilder(b=>b.UseEnvironment("Development").UseSetting("Supabase:ConnectionString",database.ConnectionString).UseSetting("Admin:UserId",""));}
    HttpClient Client(){var c=factory.CreateClient();c.DefaultRequestHeaders.Add("X-Requested-With","InterviewPrep");return c;}
    async Task<(HttpClient C,string Id)> Account(bool admin=false){var c=Client();var response=await c.PostAsJsonAsync("/api/auth/register",new{name="Compte test",email=Guid.NewGuid()+"@example.test",password="test-only-long-password",is_admin=true,is_paid=true});Assert.Equal(HttpStatusCode.OK,response.StatusCode);var id=(await response.Content.ReadFromJsonAsync<JsonObject>())!["id"]!.GetValue<string>();if(admin)factory.Services.GetRequiredService<IConfiguration>()["Admin:UserId"]=id;return(c,id);}
    object New(string? id=null,string subject="Demande de test")=>new{id=id??Guid.NewGuid().ToString(),subject,category="technical",body="Message privé de test uniquement",user_id="forged",from_admin=true};
    async Task<string> Ticket(HttpClient c){var res=await c.PostAsJsonAsync("/api/support/tickets",New());Assert.Equal(HttpStatusCode.OK,res.StatusCode);return(await res.Content.ReadFromJsonAsync<JsonObject>())!["id"]!.GetValue<string>();}
    static object Site(int version=0,string publisher="Éditeur test")=>new{publisher,country="Pays test",address="Adresse test",email="contact@example.test",registration="",version};
    [Theory][InlineData("/api/admin/overview")][InlineData("/api/admin/users")][InlineData("/api/admin/payments")][InlineData("/api/admin/tickets")]
    public async Task AnonymousAndOrdinaryUsersCannotAdmin(string path){using var anon=Client();Assert.Equal(HttpStatusCode.Unauthorized,(await anon.GetAsync(path)).StatusCode);var(c,_)=await Account();using(c)Assert.Equal(HttpStatusCode.Forbidden,(await c.GetAsync(path)).StatusCode);}
    [Fact] public async Task RegistrationCannotGrantAdminOrPaidFlags(){var(c,id)=await Account();using(c){var status=await c.GetFromJsonAsync<JsonObject>("/api/checkout/status");Assert.False(status!["is_paid"]!.GetValue<bool>());Assert.False(status["is_admin"]!.GetValue<bool>());Assert.False(status["has_access"]!.GetValue<bool>());await c.PutAsJsonAsync("/api/me",new{name="Nouveau nom",is_admin=true,is_paid=true});Assert.Equal((HttpStatusCode)402,(await c.GetAsync("/api/data")).StatusCode);}}
    [Fact] public async Task AdminAccessNeverWritesPaymentAndCheckoutNeverCallsProvider(){var(c,id)=await Account(true);using(c){var s=await c.GetFromJsonAsync<JsonObject>("/api/checkout/status");Assert.True(s!["is_admin"]!.GetValue<bool>());Assert.True(s["has_access"]!.GetValue<bool>());Assert.False(s["is_paid"]!.GetValue<bool>());Assert.Null(s["paid_at"]);Assert.True((await c.GetFromJsonAsync<JsonObject>("/api/me"))!["is_admin"]!.GetValue<bool>());Assert.Equal(HttpStatusCode.OK,(await c.GetAsync("/api/data")).StatusCode);var checkout=await c.PostAsJsonAsync("/api/checkout",new{});Assert.Equal(HttpStatusCode.OK,checkout.StatusCode);Assert.Equal("admin_access",(await checkout.Content.ReadFromJsonAsync<JsonObject>())!["data"]!["step"]!.GetValue<string>());Assert.Equal(0,database.Scalar("SELECT count(*) FROM payment_receipts"));Assert.Equal(0,database.Scalar("SELECT count(*) FROM users WHERE is_paid"));}}
    [Fact] public async Task AdminIsExactlyOneIdAndRevocationWorksWithExistingCookies(){var(a,aid)=await Account(true);var(b,bid)=await Account();using(a)using(b){Assert.Equal(HttpStatusCode.OK,(await a.GetAsync("/api/admin/overview")).StatusCode);Assert.Equal(HttpStatusCode.Forbidden,(await b.GetAsync("/api/admin/overview")).StatusCode);factory.Services.GetRequiredService<IConfiguration>()["Admin:UserId"]=bid;Assert.Equal(HttpStatusCode.Forbidden,(await a.GetAsync("/api/admin/overview")).StatusCode);Assert.Equal((HttpStatusCode)402,(await a.GetAsync("/api/data")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await b.GetAsync("/api/admin/overview")).StatusCode);}}
    [Theory][InlineData("")][InlineData("admin@example.test")][InlineData("00000000-0000-0000-0000-000000000000")][InlineData("first,second")]
    public async Task BadAdminConfigurationFailsClosed(string config){var(c,_)=await Account();using(c){factory.Services.GetRequiredService<IConfiguration>()["Admin:UserId"]=config;Assert.Equal(HttpStatusCode.Forbidden,(await c.GetAsync("/api/admin/users")).StatusCode);Assert.Equal((HttpStatusCode)402,(await c.GetAsync("/api/data")).StatusCode);}}
    [Fact] public async Task SupportIsFreePrivateAndIgnoresForgedOwnership(){var(a,aid)=await Account();var(b,bid)=await Account();using(a)using(b){var id=await Ticket(a);var list=await a.GetFromJsonAsync<JsonObject>("/api/support/tickets");Assert.Equal(1,list!["total"]!.GetValue<int>());Assert.Equal(0,(await b.GetFromJsonAsync<JsonObject>("/api/support/tickets"))!["total"]!.GetValue<int>());var detail=await a.GetFromJsonAsync<JsonObject>("/api/support/tickets/"+id);Assert.False(detail!["messages"]![0]!["from_admin"]!.GetValue<bool>());Assert.Null(detail["customer"]);Assert.Equal(HttpStatusCode.NotFound,(await b.GetAsync("/api/support/tickets/"+id)).StatusCode);Assert.Equal(HttpStatusCode.NotFound,(await b.PostAsJsonAsync($"/api/support/tickets/{id}/messages",new{id=Guid.NewGuid(),body="Intrusion"})).StatusCode);Assert.Equal(HttpStatusCode.NotFound,(await b.PatchAsJsonAsync("/api/support/tickets/"+id,new{status="closed"})).StatusCode);}}
    [Fact] public async Task RepeatedAndConcurrentCreationAreAtomic(){var(c,id)=await Account();using(c){var input=New();var responses=await Task.WhenAll(Enumerable.Range(0,5).Select(_=>c.PostAsJsonAsync("/api/support/tickets",input)));Assert.All(responses,r=>Assert.Equal(HttpStatusCode.OK,r.StatusCode));Assert.Equal(1,database.Scalar("SELECT count(*) FROM support_tickets"));Assert.Equal(1,database.Scalar("SELECT count(*) FROM support_messages"));}}
    [Fact] public async Task IdempotencyConflictsCannotReplaceOrReadAnotherTicket(){var(a,_)=await Account();var(b,_b)=await Account();using(a)using(b){var id=await Ticket(a);Assert.Equal(HttpStatusCode.Conflict,(await a.PostAsJsonAsync("/api/support/tickets",New(id,"Autre sujet"))).StatusCode);Assert.Equal(HttpStatusCode.Conflict,(await b.PostAsJsonAsync("/api/support/tickets",New(id))).StatusCode);Assert.Equal(1,database.Scalar("SELECT count(*) FROM support_messages"));}}
    [Fact] public async Task AdminRepliesCustomerRepliesClosesAndReopens(){var(c,_)=await Account();var(a,_a)=await Account(true);using(c)using(a){var id=await Ticket(c);var msg=new{id=Guid.NewGuid(),body="Réponse du support"};var replies=await Task.WhenAll(Enumerable.Range(0,3).Select(_=>a.PostAsJsonAsync($"/api/support/tickets/{id}/messages",msg)));Assert.All(replies,r=>Assert.Equal(HttpStatusCode.OK,r.StatusCode));var detail=await c.GetFromJsonAsync<JsonObject>("/api/support/tickets/"+id);Assert.Equal("waiting",detail!["ticket"]!["status"]!.GetValue<string>());Assert.Equal(2,detail["messages"]!.AsArray().Count);Assert.True(detail["messages"]![1]!["from_admin"]!.GetValue<bool>());Assert.Equal(HttpStatusCode.OK,(await c.PostAsJsonAsync($"/api/support/tickets/{id}/messages",new{id=Guid.NewGuid(),body="Merci pour votre réponse"})).StatusCode);Assert.Equal("open",(await a.GetFromJsonAsync<JsonObject>("/api/support/tickets/"+id))!["ticket"]!["status"]!.GetValue<string>());Assert.Equal(HttpStatusCode.OK,(await c.PatchAsJsonAsync("/api/support/tickets/"+id,new{status="closed"})).StatusCode);Assert.Equal(HttpStatusCode.Conflict,(await a.PostAsJsonAsync($"/api/support/tickets/{id}/messages",new{id=Guid.NewGuid(),body="Après fermeture"})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await a.PostAsJsonAsync($"/api/support/tickets/{id}/messages",msg)).StatusCode);Assert.Equal(HttpStatusCode.OK,(await c.PatchAsJsonAsync("/api/support/tickets/"+id,new{status="open"})).StatusCode);}}
    [Fact] public async Task AnonymousAndCsrfWritesAreBlocked(){using var anon=Client();Assert.Equal(HttpStatusCode.Unauthorized,(await anon.PostAsJsonAsync("/api/support/tickets",New())).StatusCode);var(c,_)=await Account(true);using(c){c.DefaultRequestHeaders.Remove("X-Requested-With");Assert.Equal(HttpStatusCode.Forbidden,(await c.PostAsJsonAsync("/api/support/tickets",New())).StatusCode);Assert.Equal(HttpStatusCode.Forbidden,(await c.PutAsJsonAsync("/api/admin/site",Site())).StatusCode);}}
    [Fact] public async Task InvalidInputsAreRejectedWithoutWriting(){var(c,_)=await Account();using(c){Assert.Equal(HttpStatusCode.BadRequest,(await c.PostAsJsonAsync("/api/support/tickets",new{id=Guid.NewGuid(),subject="abc",body="x",category="invalid"})).StatusCode);Assert.Equal(HttpStatusCode.BadRequest,(await c.GetAsync("/api/support/tickets/bad-id")).StatusCode);Assert.Equal(HttpStatusCode.BadRequest,(await c.GetAsync("/api/support/tickets?page=-1")).StatusCode);Assert.Equal(0,database.Scalar("SELECT count(*) FROM support_tickets"));}}
    [Fact] public async Task UnicodeMinimumLengthIsRejectedAsValidationNotDatabaseFailure(){var(c,_)=await Account();using(c){var r=await c.PostAsJsonAsync("/api/support/tickets",new{id=Guid.NewGuid(),subject="😀😀",category="technical",body="Message de test valide"});Assert.Equal(HttpStatusCode.BadRequest,r.StatusCode);Assert.Equal(0,database.Scalar("SELECT count(*) FROM support_tickets"));}}
    [Fact] public async Task SettingsArePublicButOnlyAdminCanWriteAndStaleChangesAreRejected(){var(c,_)=await Account();var(a,_a)=await Account(true);using(c)using(a){var initial=await c.GetFromJsonAsync<JsonObject>("/api/site");Assert.Equal("",initial!["publisher"]!.GetValue<string>());Assert.Equal(HttpStatusCode.Forbidden,(await c.PutAsJsonAsync("/api/admin/site",Site())).StatusCode);Assert.Equal(HttpStatusCode.OK,(await a.PutAsJsonAsync("/api/admin/site",Site())).StatusCode);Assert.Equal(HttpStatusCode.Conflict,(await a.PutAsJsonAsync("/api/admin/site",Site())).StatusCode);Assert.Equal(HttpStatusCode.OK,(await a.PutAsJsonAsync("/api/admin/site",Site(1,"Nouveau nom"))).StatusCode);using var anon=Client();var site=await anon.GetFromJsonAsync<JsonObject>("/api/site");Assert.Equal("Nouveau nom",site!["publisher"]!.GetValue<string>());Assert.Equal(2,site["version"]!.GetValue<int>());}}
    [Fact] public async Task AdminListsContainRealCountsButNoPasswordsOrPrivateCreations(){var(a,aid)=await Account(true);var(c,id)=await Account();using(a)using(c){factory.Services.GetRequiredService<Store>().Save(id,"cv",new JsonObject{["id"]="test-sensitive",["analysis"]="private-DO-NOT-EXPOSE"});await Ticket(c);var stats=await a.GetFromJsonAsync<JsonObject>("/api/admin/overview");Assert.Equal(2,stats!["users"]!.GetValue<int>());Assert.Equal(1,stats["cvs"]!.GetValue<int>());Assert.Equal(1,stats["open_tickets"]!.GetValue<int>());foreach(var path in new[]{"overview","users","payments","tickets"}){var text=await a.GetStringAsync("/api/admin/"+path);Assert.DoesNotContain("private-DO-NOT-EXPOSE",text);Assert.DoesNotContain("\"salt\"",text);Assert.DoesNotContain("\"hash\"",text);Assert.DoesNotContain("payload_sha256",text);}Assert.Equal(1,(await a.GetFromJsonAsync<JsonObject>("/api/admin/users?access=admin"))!["total"]!.GetValue<int>());Assert.Equal(1,(await a.GetFromJsonAsync<JsonObject>("/api/admin/users?access=unpaid"))!["total"]!.GetValue<int>());Assert.Equal(0,(await a.GetFromJsonAsync<JsonObject>("/api/admin/users?q=%27%20OR%201%3D1%20--"))!["total"]!.GetValue<int>());}}
    [Fact] public async Task ExportIsOwnerOnlyAndDeletingAccountCascadesSupport(){var(a,_)=await Account(true);var(c,_c)=await Account();using(a)using(c){await Ticket(c);Assert.Empty((await a.GetFromJsonAsync<JsonObject>("/api/support/export"))!["tickets"]!.AsArray());Assert.Single((await c.GetFromJsonAsync<JsonObject>("/api/support/export"))!["tickets"]!.AsArray());await c.DeleteAsync("/api/me");Assert.Equal(0,database.Scalar("SELECT count(*) FROM support_tickets"));Assert.Equal(0,database.Scalar("SELECT count(*) FROM support_messages"));}}
    [Fact] public async Task MigrationIsRepeatableAndProtectsNewTables(){var(c,id)=await Account();using(c){await Ticket(c);database.Execute(File.ReadAllText(Path.Combine(AppContext.BaseDirectory,"schema.sql")));Assert.Equal(1,database.Scalar("SELECT count(*) FROM support_messages"));Assert.Equal(3,database.Scalar("SELECT count(*) FROM pg_class WHERE relname IN ('support_tickets','support_messages','site_settings') AND relrowsecurity"));}}
    [Fact] public async Task AdminCompletesInterviewWithoutPayingUsingStubbedAi(){var handler=new AiStub();var config=new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{{"Gemini:ApiKey","test-only"}}).Build();using var app=factory.WithWebHostBuilder(b=>b.ConfigureServices(s=>s.AddTransient<Gemini>(_=>new Gemini(new HttpClient(handler),config))));using var c=app.CreateClient();c.DefaultRequestHeaders.Add("X-Requested-With","InterviewPrep");var reg=await c.PostAsJsonAsync("/api/auth/register",new{name="Admin test",email="admin-test@example.test",password="test-only-long-password"});var id=(await reg.Content.ReadFromJsonAsync<JsonObject>())!["id"]!.GetValue<string>();app.Services.GetRequiredService<IConfiguration>()["Admin:UserId"]=id;using var form=new MultipartFormDataContent();form.Add(new ByteArrayContent(Encoding.ASCII.GetBytes("%PDF-test-only")),"file","cv.pdf");form.Add(new StringContent("true"),"consent");var cvResponse=await c.PostAsync("/api/cvs",form);Assert.Equal(HttpStatusCode.OK,cvResponse.StatusCode);var cv=await cvResponse.Content.ReadFromJsonAsync<JsonObject>();var started=await c.PostAsJsonAsync("/api/sessions",new{cvId=cv!["id"]!.GetValue<string>(),role="Poste test",level="Débutant",count=5});Assert.Equal(HttpStatusCode.OK,started.StatusCode);var session=(await started.Content.ReadFromJsonAsync<JsonObject>())!["id"]!.GetValue<string>();Assert.Equal(HttpStatusCode.OK,(await c.PutAsJsonAsync($"/api/sessions/{session}/answers",new{values=Enumerable.Repeat("Une réponse de test suffisamment longue.",5)})).StatusCode);var evaluated=await c.PostAsync($"/api/sessions/{session}/evaluate",null);Assert.Equal(HttpStatusCode.OK,evaluated.StatusCode);Assert.Equal(80,(await evaluated.Content.ReadFromJsonAsync<JsonObject>())!["result"]!["score"]!.GetValue<int>());Assert.Equal(0,database.Scalar("SELECT count(*) FROM users WHERE is_paid"));Assert.Equal(0,database.Scalar("SELECT count(*) FROM payment_receipts"));Assert.Equal(2,database.Scalar("SELECT count(*) FROM records"));}
    class AiStub:HttpMessageHandler {
        int call;
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken ct){
            string text=call++ switch {
                0=>"{\"isCv\":true,\"role\":\"Test\",\"summary\":\"Test\",\"skills\":[\"Test\"],\"tips\":[\"Test\"]}",
                1=>JsonSerializer.Serialize(new{questions=Enumerable.Range(1,5).Select(i=>new{category="Test",text="Question test "+i,hint="Test"})}),
                _=>JsonSerializer.Serialize(new{score=0,summary="Test",criteria=new[]{new{name="Pertinence",score=60,comment="Test"},new{name="Structure",score=80,comment="Test"},new{name="Précision",score=100,comment="Test"}},strengths=new[]{"Test"},improvements=new[]{"Test"},feedback=Enumerable.Range(1,5).Select(i=>new{comment="Test",example="Test"})})};
            return Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=JsonContent.Create(new{candidates=new[]{new{finishReason="STOP",content=new{parts=new[]{new{text}}}}}})});
        }
    }
    public void Dispose(){factory.Dispose();database.Dispose();}
}
