using System.Net;
using System.Net.Http.Json;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json.Nodes;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

public sealed class PaymentTests:IDisposable {
    const string Secret="whsec_unit_test_only",Product="prd_unit_test";
    readonly TestDatabase database=new();
    readonly WebApplicationFactory<Program> factory;
    readonly ProviderStub provider=new();
    public PaymentTests(){factory=new WebApplicationFactory<Program>().WithWebHostBuilder(b=>b.UseEnvironment("Development").UseSetting("Supabase:ConnectionString",database.ConnectionString).UseSetting("Chariow:ApiKey","sk_test_only").UseSetting("Chariow:ProductId",Product).UseSetting("Chariow:PulseSecret",Secret).UseSetting("App:PublicUrl","https://app.example.test").ConfigureServices(s=>s.AddHttpClient("chariow").ConfigurePrimaryHttpMessageHandler(()=>provider)));}
    HttpClient Client(bool csrf=true){var c=factory.CreateClient();if(csrf)c.DefaultRequestHeaders.Add("X-Requested-With","InterviewPrep");return c;}
    async Task<(HttpClient Client,string Id,string Email)> Account(bool paid=false){var c=Client();var email=Guid.NewGuid()+"@example.test";var r=await c.PostAsJsonAsync("/api/auth/register",new{name="Test compte",email,password="a-test-password-123"});Assert.Equal(HttpStatusCode.OK,r.StatusCode);var u=(await r.Content.ReadFromJsonAsync<JsonObject>())!;var id=u["id"]!.GetValue<string>();if(paid)factory.Services.GetRequiredService<Store>().Execute("UPDATE public.users SET is_paid=true,paid_at=CURRENT_TIMESTAMP WHERE id=@id",("id",id));return(c,id,email);}
    static object Customer(string email)=>new{firstName="Test",lastName="Client",email,phone="0612345678",countryCode="FR",custom_metadata=new{user_id="attacker-cannot-set-this"}};
    static JsonObject Payload(string user,string sale="sal_test",string evt="sale.completed",string product=Product)=>evt=="successful.sale"?new(){["event"]=evt,["sale"]=new JsonObject{["id"]=sale,["status"]="completed",["custom_metadata"]=new JsonObject{["user_id"]=user}},["product"]=new JsonObject{["id"]=product}}:new(){["event"]=evt,["data"]=new JsonObject{["id"]=sale,["status"]="completed",["product"]=new JsonObject{["id"]=product},["custom_metadata"]=new JsonObject{["user_id"]=user}}};
    async Task<HttpResponseMessage> Pulse(JsonObject payload,string? signature=null,string delivery="delivery-test"){
        using var c=Client(false);var raw=payload.ToJsonString();var req=new HttpRequestMessage(HttpMethod.Post,"/api/pulse"){Content=new StringContent(raw,Encoding.UTF8,"application/json")};
        req.Headers.Add("X-Chariow-Signature",signature??("sha256="+Convert.ToHexString(HMACSHA256.HashData(Encoding.UTF8.GetBytes(Secret),Encoding.UTF8.GetBytes(raw))).ToLowerInvariant()));req.Headers.Add("X-Pulse-Delivery-Id",delivery);return await c.SendAsync(req);
    }
    User User(string id)=>factory.Services.GetRequiredService<Store>().UserById(id)!;
    [Fact] public async Task CheckoutWithoutAuthenticationIs401(){using var c=Client(false);Assert.Equal(HttpStatusCode.Unauthorized,(await c.PostAsJsonAsync("/api/checkout",Customer("unknown@example.test"))).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await c.GetAsync("/api/checkout/status")).StatusCode);}
    [Fact] public async Task CheckoutPaidUserIsAlreadyPaidWithoutProviderCall(){var(c,id,email)=await Account(true);using(c){var r=await c.PostAsJsonAsync("/api/checkout",Customer(email));Assert.Equal(HttpStatusCode.OK,r.StatusCode);var body=await r.Content.ReadFromJsonAsync<JsonObject>();Assert.Equal("already_paid",body!["data"]!["step"]!.GetValue<string>());Assert.Equal(0,provider.Checkouts);}}
    [Theory][InlineData("/api/data","GET")][InlineData("/api/cvs","POST")][InlineData("/api/sessions","POST")][InlineData("/api/sessions/test/answers","PUT")][InlineData("/api/sessions/test/evaluate","POST")]
    public async Task PaywallUsesRealApiRoutes(string path,string method){var(c,_,_)=await Account();using(c){var r=await c.SendAsync(new HttpRequestMessage(new HttpMethod(method),path){Content=JsonContent.Create(new{})});Assert.Equal((HttpStatusCode)402,r.StatusCode);Assert.Equal("PAYMENT_REQUIRED",(await r.Content.ReadFromJsonAsync<JsonObject>())!["code"]!.GetValue<string>());}}
    [Fact] public async Task UnpaidUserCanCheckStatusExportAndDeleteData(){var(c,_,_)=await Account();using(c){var status=await c.GetFromJsonAsync<JsonObject>("/api/checkout/status");Assert.False(status!["is_paid"]!.GetValue<bool>());Assert.Null(status["paid_at"]);Assert.Equal(HttpStatusCode.OK,(await c.GetAsync("/api/me")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await c.GetAsync("/api/account/export")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await c.DeleteAsync("/api/records/not-found")).StatusCode);}}
    [Fact] public async Task OfferUsesRealProductEndpointWithoutExposingApiKey(){using var c=Client();var response=await c.GetAsync("/api/checkout/offer");Assert.Equal(HttpStatusCode.OK,response.StatusCode);var text=await response.Content.ReadAsStringAsync();Assert.Contains("29",text);Assert.DoesNotContain("sk_test_only",text);}
    [Fact] public async Task CheckoutSetsServerMetadataAndReusesActiveCheckout(){var(c,id,email)=await Account();using(c){var a=await c.PostAsJsonAsync("/api/checkout",Customer(email));Assert.Equal(HttpStatusCode.OK,a.StatusCode);var body=await a.Content.ReadFromJsonAsync<JsonObject>();Assert.Equal("payment",body!["data"]!["step"]!.GetValue<string>());Assert.Equal("https://store.mychariow.com/checkout/test",body["data"]!["payment"]!["checkout_url"]!.GetValue<string>());Assert.Equal(id,provider.LastCheckout!["custom_metadata"]!["user_id"]!.GetValue<string>());Assert.Equal("https://app.example.test/#merci",provider.LastCheckout["redirect_url"]!.GetValue<string>());Assert.Equal("FR",provider.LastCheckout["phone"]!["country_code"]!.GetValue<string>());var b=await c.PostAsJsonAsync("/api/checkout",Customer(email));Assert.Equal(HttpStatusCode.OK,b.StatusCode);Assert.Equal(1,provider.Checkouts);Assert.False(User(id).IsPaid);}}
    [Fact] public async Task ProviderAlreadyPurchasedNeverGrantsAccessByEmail(){provider.Step="already_purchased";var(c,id,email)=await Account();using(c){var r=await c.PostAsJsonAsync("/api/checkout",Customer(email));Assert.Equal(HttpStatusCode.Conflict,r.StatusCode);Assert.False(User(id).IsPaid);}}
    [Fact] public async Task CompletedCheckoutStillWaitsForSignedPulse(){provider.Step="completed";var(c,id,email)=await Account();using(c){var r=await c.PostAsJsonAsync("/api/checkout",Customer(email));Assert.Equal(HttpStatusCode.OK,r.StatusCode);Assert.False(User(id).IsPaid);}}
    [Fact] public async Task CheckoutRejectsWrongEmailAndMissingCsrf(){var(c,id,email)=await Account();using(c){Assert.Equal(HttpStatusCode.BadRequest,(await c.PostAsJsonAsync("/api/checkout",Customer("other@example.test"))).StatusCode);c.DefaultRequestHeaders.Remove("X-Requested-With");Assert.Equal(HttpStatusCode.Forbidden,(await c.PostAsJsonAsync("/api/checkout",Customer(email))).StatusCode);Assert.Equal(0,provider.Checkouts);}}
    [Theory][InlineData("")][InlineData("sha256=wrong")][InlineData("sha256=0000000000000000000000000000000000000000000000000000000000000000")]
    public async Task InvalidSignatureIs401(string signature){var(c,id,_)=await Account();using(c){Assert.Equal(HttpStatusCode.Unauthorized,(await Pulse(Payload(id),signature)).StatusCode);Assert.False(User(id).IsPaid);}}
    [Theory][InlineData("sale.completed")][InlineData("successful.sale")]
    public async Task CompletedPulseActivatesPostgres(string evt){var(c,id,_)=await Account();using(c){var r=await Pulse(Payload(id,evt:evt));Assert.Equal(HttpStatusCode.OK,r.StatusCode);var u=User(id);Assert.True(u.IsPaid);Assert.NotNull(u.PaidAt);Assert.Equal("sal_test",u.ChariowSaleId);Assert.Equal(HttpStatusCode.OK,(await c.GetAsync("/api/data")).StatusCode);}}
    [Fact] public async Task RepeatedSaleIsIdempotentAcrossDeliveryIds(){var(c,id,_)=await Account();using(c){Assert.Equal(HttpStatusCode.OK,(await Pulse(Payload(id))).StatusCode);var original=User(id).PaidAt;var r=await Pulse(Payload(id),delivery:"new-delivery-id");Assert.Equal(HttpStatusCode.OK,r.StatusCode);Assert.True((await r.Content.ReadFromJsonAsync<JsonObject>())!["duplicate"]!.GetValue<bool>());Assert.Equal(original,User(id).PaidAt);Assert.Equal(1,database.Scalar("SELECT count(*) FROM payment_receipts"));}}
    [Fact] public async Task ConcurrentPulsesActivateExactlyOnce(){var(c,id,_)=await Account();using(c){var replies=await Task.WhenAll(Enumerable.Range(0,8).Select(i=>Pulse(Payload(id),delivery:"delivery-"+i)));Assert.All(replies,r=>Assert.Equal(HttpStatusCode.OK,r.StatusCode));var bodies=await Task.WhenAll(replies.Select(r=>r.Content.ReadFromJsonAsync<JsonObject>()));Assert.Single(bodies,b=>b!["activated"]!.GetValue<bool>());Assert.Equal(1,database.Scalar("SELECT count(*) FROM payment_receipts"));}}
    [Fact] public async Task SameSaleCannotUnlockAnotherAccount(){var(a,id,_)=await Account();var(b,other,_)=await Account();using(a)using(b){Assert.Equal(HttpStatusCode.OK,(await Pulse(Payload(id))).StatusCode);Assert.Equal(HttpStatusCode.Conflict,(await Pulse(Payload(other))).StatusCode);Assert.False(User(other).IsPaid);}}
    [Fact] public async Task SecondSaleDoesNotOverwriteOriginalPaymentDate(){var(c,id,_)=await Account();using(c){await Pulse(Payload(id));var first=User(id);await Pulse(Payload(id,"sal_second"));var second=User(id);Assert.Equal(first.PaidAt,second.PaidAt);Assert.Equal(first.ChariowSaleId,second.ChariowSaleId);Assert.Equal(2,database.Scalar("SELECT count(*) FROM payment_receipts"));}}
    [Fact] public async Task OtherEventsAndProductsNeverActivate(){var(c,id,_)=await Account();using(c){Assert.Equal(HttpStatusCode.OK,(await Pulse(Payload(id,product:"prd_other"))).StatusCode);Assert.Equal(HttpStatusCode.OK,(await Pulse(Payload(id,evt:"sale.failed"))).StatusCode);Assert.False(User(id).IsPaid);}}
    [Fact] public async Task MissingMetadataOrIncompleteSaleNeverActivates(){var(c,id,_)=await Account();using(c){var p=Payload(id);p["data"]!["custom_metadata"]=null;Assert.Equal((HttpStatusCode)422,(await Pulse(p)).StatusCode);p=Payload(id);p["data"]!["status"]="awaiting_payment";Assert.Equal((HttpStatusCode)422,(await Pulse(p)).StatusCode);Assert.False(User(id).IsPaid);}}
    [Fact] public async Task DatabaseFailureRollsBackReceiptAndCanBeRetried(){var(c,id,_)=await Account();using(c){database.Execute("CREATE FUNCTION public.reject_activation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'test rollback'; END $$; CREATE TRIGGER reject_activation BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.reject_activation();");Assert.Equal(HttpStatusCode.InternalServerError,(await Pulse(Payload(id))).StatusCode);Assert.Equal(0,database.Scalar("SELECT count(*) FROM payment_receipts"));Assert.False(User(id).IsPaid);database.Execute("DROP TRIGGER reject_activation ON public.users");Assert.Equal(HttpStatusCode.OK,(await Pulse(Payload(id))).StatusCode);Assert.True(User(id).IsPaid);}}
    [Fact] public async Task DashboardTestWithNoRealMetadataIsIgnored(){var(c,id,_)=await Account();using(c){var payload=new JsonObject{["event"]="successful.sale",["note"]="Test event",["sale"]=new JsonObject{["id"]="test"}};Assert.Equal(HttpStatusCode.OK,(await Pulse(payload)).StatusCode);Assert.False(User(id).IsPaid);}}
    [Fact] public async Task UnknownUserDoesNotCreateReceipt(){Assert.Equal(HttpStatusCode.NotFound,(await Pulse(Payload(Guid.NewGuid().ToString()))).StatusCode);Assert.Equal(0,database.Scalar("SELECT count(*) FROM payment_receipts"));}
    [Fact] public async Task MissingDeliveryHeaderIsAllowedButSaleRemainsUnique(){var(c,id,_)=await Account();using(c){Assert.Equal(HttpStatusCode.OK,(await Pulse(Payload(id),delivery:"")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await Pulse(Payload(id),delivery:"")).StatusCode);Assert.Equal(1,database.Scalar("SELECT count(*) FROM payment_receipts"));}}
    [Fact] public async Task DeletedAccountSaleCannotBeReassigned(){var(c,id,_)=await Account();using(c){await Pulse(Payload(id));Assert.Equal(HttpStatusCode.OK,(await c.DeleteAsync("/api/me")).StatusCode);var(other,otherId,_)=await Account();using(other){Assert.Equal(HttpStatusCode.OK,(await Pulse(Payload(otherId))).StatusCode);Assert.False(User(otherId).IsPaid);Assert.Equal(1,database.Scalar("SELECT count(*) FROM payment_receipts WHERE user_id IS NULL"));}}}
    [Fact] public async Task PaidCheckoutDoesNotRequireCustomerFields(){var(c,_,_)=await Account(true);using(c){Assert.Equal(HttpStatusCode.OK,(await c.PostAsJsonAsync("/api/checkout",new{})).StatusCode);Assert.Equal(0,provider.Checkouts);}}
    [Fact] public async Task CheckoutConcurrentRequestsReuseSingleProviderSession(){var(c,id,email)=await Account();using(c){var replies=await Task.WhenAll(Enumerable.Range(0,6).Select(_=>c.PostAsJsonAsync("/api/checkout",Customer(email))));Assert.All(replies,r=>Assert.Equal(HttpStatusCode.OK,r.StatusCode));Assert.Equal(1,provider.Checkouts);Assert.False(User(id).IsPaid);}}
    [Fact] public async Task OnlyPostPulseIsExemptFromCsrf(){using var c=Client(false);Assert.Equal(HttpStatusCode.Forbidden,(await c.PutAsJsonAsync("/api/pulse",new{})).StatusCode);}
    [Theory][InlineData("shipping",502)][InlineData("fields",503)][InlineData("pricing",502)][InlineData("draft",503)]
    public async Task UnsupportedOrMalformedProductFailsSafely(string scenario,int status){provider.ProductOverride=JsonNode.Parse("{\"id\":\"prd_unit_test\",\"name\":\"Test\",\"status\":\"published\",\"type\":\"license\",\"settings\":{\"is_requires_shipping_address\":false},\"pricing\":{\"type\":\"one_time\",\"current_price\":{\"value\":29,\"formatted\":\"29 EUR\",\"currency\":\"EUR\"}}}")!.AsObject();switch(scenario){case "shipping":provider.ProductOverride["settings"]!["is_requires_shipping_address"]="not-a-boolean";break;case "fields":provider.ProductOverride["fields"]=new JsonArray("unsupported");break;case "pricing":provider.ProductOverride["pricing"]="wrong shape";break;case "draft":provider.ProductOverride["status"]="draft";break;}using var c=Client();Assert.Equal((HttpStatusCode)status,(await c.GetAsync("/api/checkout/offer")).StatusCode);}
    [Fact] public async Task MalformedCheckoutPaymentIs502NotAnUnhandled500(){provider.CheckoutOverride=new JsonObject{["step"]="payment",["payment"]="wrong shape"};var(c,id,email)=await Account();using(c){Assert.Equal(HttpStatusCode.BadGateway,(await c.PostAsJsonAsync("/api/checkout",Customer(email))).StatusCode);Assert.False(User(id).IsPaid);}}
    [Fact] public async Task CookieKeysSurviveASecondApplicationInstance(){var(c,id,email)=await Account();using(c){var login=await c.PostAsJsonAsync("/api/auth/login",new{email,password="a-test-password-123"});var cookie=login.Headers.GetValues("Set-Cookie").Single().Split(';')[0];using var otherFactory=factory.WithWebHostBuilder(_=>{});using var other=otherFactory.CreateClient();other.DefaultRequestHeaders.Add("Cookie",cookie);Assert.Equal(HttpStatusCode.OK,(await other.GetAsync("/api/checkout/status")).StatusCode);Assert.True(database.Scalar("SELECT count(*) FROM data_protection_keys")>0);}}
    static JsonObject DigitalProduct()=>JsonNode.Parse("{\"id\":\"prd_unit_test\",\"name\":\"Test\",\"status\":\"published\",\"type\":\"license\",\"settings\":{},\"pricing\":{\"type\":\"one_time\",\"current_price\":{\"value\":29,\"formatted\":\"29 EUR\",\"currency\":\"EUR\"}}}")!.AsObject();
    [Theory][InlineData("null")][InlineData("0")][InlineData("false")][InlineData("\"false\"")][InlineData("\"0\"")][InlineData("missing-flag")][InlineData("missing-settings")][InlineData("null-settings")]
    public async Task OptionalShippingFlagAllowsOfferAndCheckoutWithoutActivatingUser(string representation){
        provider.ProductOverride=DigitalProduct();
        if(representation=="missing-settings")provider.ProductOverride.Remove("settings");
        else if(representation=="null-settings")provider.ProductOverride["settings"]=null;
        else if(representation!="missing-flag")provider.ProductOverride["settings"]!["is_requires_shipping_address"]=JsonNode.Parse(representation);
        var(c,id,email)=await Account();using(c){
            var offer=await c.GetAsync("/api/checkout/offer");Assert.Equal(HttpStatusCode.OK,offer.StatusCode);
            var price=(await offer.Content.ReadFromJsonAsync<JsonObject>())!["price"]!;Assert.Equal(29,price["value"]!.GetValue<decimal>());
            Assert.Equal(HttpStatusCode.OK,(await c.PostAsJsonAsync("/api/checkout",Customer(email))).StatusCode);
            Assert.Equal(1,provider.Checkouts);Assert.Equal(id,provider.LastCheckout!["custom_metadata"]!["user_id"]!.GetValue<string>());Assert.False(User(id).IsPaid);
        }
    }
    [Theory][InlineData("true")][InlineData("1")][InlineData("\"true\"")][InlineData("\"1\"")]
    public async Task ShippingRequirementStillBlocksRemoteCheckout(string representation){
        provider.ProductOverride=DigitalProduct();provider.ProductOverride["settings"]!["is_requires_shipping_address"]=JsonNode.Parse(representation);
        var(c,id,email)=await Account();using(c){
            Assert.Equal(HttpStatusCode.ServiceUnavailable,(await c.GetAsync("/api/checkout/offer")).StatusCode);
            Assert.Equal(HttpStatusCode.ServiceUnavailable,(await c.PostAsJsonAsync("/api/checkout",Customer(email))).StatusCode);
            Assert.Equal(0,provider.Checkouts);Assert.False(User(id).IsPaid);
        }
    }
    [Fact] public void HmacDependsOnRawBytes(){var raw=Encoding.UTF8.GetBytes("{\"a\":1}");var signature="sha256="+Convert.ToHexString(HMACSHA256.HashData(Encoding.UTF8.GetBytes(Secret),raw)).ToLowerInvariant();Assert.True(PulseVerifier.Verify(raw,signature,Secret));Assert.False(PulseVerifier.Verify(Encoding.UTF8.GetBytes("{ \"a\": 1 }"),signature,Secret));}
    public void Dispose(){factory.Dispose();database.Dispose();}
    class ProviderStub:HttpMessageHandler {
        public int Checkouts;public string Step="payment";public JsonObject? LastCheckout;public JsonObject? ProductOverride,CheckoutOverride;
        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken ct){
            Assert.Equal("Bearer",request.Headers.Authorization?.Scheme);Assert.Equal("sk_test_only",request.Headers.Authorization?.Parameter);Assert.DoesNotContain("sk_test_only",request.RequestUri!.ToString());
            if(request.Method==HttpMethod.Get){Assert.EndsWith("/products/"+Product,request.RequestUri.AbsolutePath);if(ProductOverride!=null)return new(HttpStatusCode.OK){Content=JsonContent.Create(new{data=ProductOverride})};return new(HttpStatusCode.OK){Content=JsonContent.Create(new{data=new{id=Product,name="Accès test",type="license",status="published",pricing=new{type="one_time",current_price=new{value=29,formatted="29 €",currency="EUR"}},settings=new{is_requires_shipping_address=false}}})};}
            Assert.Equal("/v1/checkout",request.RequestUri.AbsolutePath);Checkouts++;LastCheckout=JsonNode.Parse(await request.Content!.ReadAsStringAsync(ct))!.AsObject();
            if(CheckoutOverride!=null)return new(HttpStatusCode.OK){Content=JsonContent.Create(new{data=CheckoutOverride})};
            return new(HttpStatusCode.OK){Content=JsonContent.Create(new{data=new{step=Step,purchase=new{id="sal_checkout",status=Step=="completed"?"completed":"awaiting_payment"},payment=new{checkout_url=Step=="payment"?"https://store.mychariow.com/checkout/test":null}}})};
        }
    }
}
